import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/Header";
import ReactQueryProvider from "./query/ReactQueryProvider";
import { AuthContext } from "./context/AuthContext";
import Footer from "./components/footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <ReactQueryProvider>
                    <AuthContext>
                        <Header />
                        {children}
                        <Footer />
                    </AuthContext>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
